production:
  adapter: mysql2
  host: <%= ENV['PRD_DATABASE_HOST'] %> # ホスト
  username: <%= ENV['PRD_DATABASE_USERNAME'] %> #ユーザー名
  password: <%= ENV['PRD_DATABASE_PASSWORD'] %> #パスワード
  database: <%= ENV['PRD_DATABASE_NAME'] %> #データベース名
  encoding: utf8

development:
  adapter: mysql2
  host: <%= ENV['DEV_DATABASE_HOST'] %> # ホスト
  username: <%= ENV['DEV_DATABASE_USERNAME'] %> #ユーザー名
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %> #パスワード
  database: <%= ENV['DEV_DATABASE_NAME'] %> #データベース名
  encoding: utf8
